/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/AJ.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Aj({ characterRef, isColliding }) {
  const group = React.useRef();
  const { scene, animations: loadedAnimations } = useGLTF("src/assets/AJ.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(loadedAnimations, group);

  console.log(loadedAnimations);

  React.useEffect(() => {
    const dance = actions["dance"];
    const jump = actions["angry"];

    if (actions && dance) {
      dance.play();
      if (isColliding) {
        dance.crossFadeTo(jump, 0.8);
        jump.reset();
        jump.play();
      } else {
        if (jump.isRunning() === true) {
          console.log(jump, jump.isRunning());
          jump.crossFadeTo(dance, 0.8);
          dance.reset();
          dance.play();
        }
      }
    }
  }, [isColliding, actions]);

  return (
    <group ref={group} dispose={null} scale={0.6}>
      <group name="Scene">
        <group
          name="Armature001"
          position={[-0.677, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.mixamorigHips} ref={characterRef} />
          <skinnedMesh
            name="Boy01_Body_Geo"
            geometry={nodes.Boy01_Body_Geo.geometry}
            material={materials.Boy01_Body_MAT1}
            skeleton={nodes.Boy01_Body_Geo.skeleton}
          />
          <skinnedMesh
            name="Boy01_Brows_Geo"
            geometry={nodes.Boy01_Brows_Geo.geometry}
            material={materials.Boy01_Brows_MAT2}
            skeleton={nodes.Boy01_Brows_Geo.skeleton}
          />
          <skinnedMesh
            name="Boy01_Eyes_Geo"
            geometry={nodes.Boy01_Eyes_Geo.geometry}
            material={materials.Boy01_Eyes_MAT2}
            skeleton={nodes.Boy01_Eyes_Geo.skeleton}
          />
          <skinnedMesh
            name="h_Geo"
            geometry={nodes.h_Geo.geometry}
            material={materials.Boy01_Mouth_MAT2}
            skeleton={nodes.h_Geo.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("src/assets/AJ.glb");
